--MEMBER
CREATE TABLE COFFEMEM(
	ID VARCHAR2(30) PRIMARY KEY,
	PWD VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	AGE VARCHAR2(10) NOT NULL,
	AUTH NUMBER(1) NOT NULL
);

SELECT * FROM COFFEMEM;