--MENU테이블 생성
CREATE TABLE DRINKMENU(
	SEQ NUMBER(8) PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	SMALL NUMBER(10) NOT NULL,
	TALL NUMBER(10) NOT NULL,
	GRANDE NUMBER(10) NOT NULL
);
--시퀀스 생성
CREATE SEQUENCE SEQ_MENU
START WITH 1
INCREMENT BY 1;

--기본 데이터 추가
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'헤이즐넛 카라멜 모카',4800,5300,5800);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'카라멜 마끼아또',4300,4800,5300);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'화이트 초콜릿 모카',4300,4800,5300);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'카라멜 모카',4300,4800,5300);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'카페 모카',3800,4300,4800);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'카라멜 라떼',3800,4300,4800);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'카페 라떼',3300,3800,4300);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'카푸치노',3300,3800,4300);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'아메리카노',2800,3300,3800);
INSERT INTO DRINKMENU(SEQ,NAME,SMALL,TALL,GRANDE)
VALUES(SEQ_MENU.NEXTVAL,'오늘의 커피',2500,3000,3500);




--확인용
SELECT * FROM DRINKMENU;

ALTER TABLE DRINKMENU
ADD CONSTRAINT FK_MENU_NAME FOREIGN KEY(NAME)
REFERENCES MEMBER(NAME);


DROP TABLE DRINKMENU
CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MENU;

