--TOTAL

CREATE TABLE TOTAL_ORDER(
	SEQ NUMBER(8) PRIMARY KEY,
	USERID VARCHAR2(30),
	COFFE VARCHAR2(50) NOT NULL,
	dSIZE VARCHAR2(20) NOT NULL,
	SYRUP VARCHAR2(20) ,
	SHOT VARCHAR2(20) ,
	CREAM VARCHAR2(20) ,
	QTY NUMBER(10) NOT NULL,
	PAY NUMBER(10) NOT NULL,
	wDATE DATE NOT NULL,
	CONSTRAINT FK_order FOREIGN KEY (USERID) 
REFERENCES COFFEMEM(ID)
	);
	
CREATE SEQUENCE SEQ_TOTAL_ORDER
START WITH 1
INCREMENT BY 1;



INSERT INTO TOTAL_ORDER(SEQ, COFFE,DSIZE,SYRUP,SHOT,CREAM,QTY,PAY,WDATE)
VALUES(SEQ_TOTAL_ORDER.NEXTVAL,'아메리카노')

----------------------------
SELECT * FROM TOTAL_ORDER;

DROP SEQUENCE SEQ_TOTAL_ORDER;

DROP TABLE TOTAL_ORDER;


